### PR TITLE
Error when an known variable is set but not used by the current flow

### PR DESCRIPTION
**Pull request by kareefardi**
meta 2

### CODE REVIEW

**Comment by donn** [comment]
This breaks any instances of the same config file being used for multiple flows. What prompted this?a

**Comment by donn** [comment]
To clarify, I am including things such as `--flow OpenInKLayout`

**Comment by kareefardi** [comment]
> This breaks any instances of the same config file being used for multiple flows. What prompted this?

I was attempting to run an old design with a custom flow. It was using `GRT_REPAIR_ANTENNAS` but the step was not in the custom flow (since it was recently reworked). A user would potentially be under a false assumption that the step ran. 

I wasn't aware of the breakage but we should find a strategy for such scenario.

**Review by donn — CHANGES_REQUESTED** [review]
At any rate, this is not the solution. We can discuss other approaches

**Comment by kareefardi** [comment]
> At any rate, this is not the solution. We can discuss other approaches

I think the original problem is handling old configuration files that uses steps whose behavior have drastically changed.

**Pull request closed without merging**
