### PR TITLE
Rewrite code for parsing Tcl config files

### PR DESCRIPTION
**Pull request by htfab**
The current implementation for parsing Tcl config files fails to catch environment variables defined in subordinate `.tcl` files included from the main `.tcl` with the `source` command. This breaks openlane1 compatibility for almost every user design submitted to Tiny Tapeout.

Tcl config files are parsed using `TclUtils._eval_env()`. The current version
- modifies `os.environ` to provide inputs to the script
- runs the script
- converts `::env` to numbered variables on the tcl side
- rolls back the changes to `os.environ`
- reads the numbered variables from tcl back into python
- filters the results to entries appearing in `set ::env(...)` constructs in the script

The last step is there to filter out entries inherited from the environment, but it also filters out entries defined in included files. This python-tcl interface relying on `os.environ` modifications and rewriting `::env` to numbered variables also feels brittle in some other ways. I'm proposing to rewrite it in the following manner:

- set `env(...)` directly instead of modifying and rolling back `os.environ`
- provide a python callback function to tcl code for easier backwards communication
- patch tcl's `set` function to also call our callback
- on the python side, save all `set` calls that match `env(...)` to the returned dictionary

This makes the code more robust and only saves environment variables explicitly set by the Tcl config, making it unnecessary to use the problematic filtering step.

### CODE REVIEW

**Review by donn — APPROVED** [review]
Thank you so much for the well-written fix. Intensely appreciated.

**Comment by donn** [comment]
@htfab Do you foresee any problems with us merging this to main?

**Comment by htfab** [comment]
I have run a few tests with the patch rebased to main, and it looks ok.

**Comment by donn** [comment]
Would you mind creating that PR? I would do it myself, but it would assign authorship of the PR to me which would be unfair.

**Comment by htfab** [comment]
Ok, created #474.

**Pull request closed without merging**
