### PR TITLE
Grid pattern fix

### PR DESCRIPTION
**Pull request by mole99**
## Scripts

- `io_place.py`: Fix grid X/Y direction for vertical and horizontal grid pattern.

Also contains a small fix to the Readme.

### CODE REVIEW

**Comment by kareefardi** [comment]
@mole99 I am wondering why the flip? According the LEF/DEF reference, X indicates vertical lines which would relate to N and S for of the design pins. 
image

**Comment by mole99** [comment]
I am very sorry! I thought X/Y refers to the axis on which the pins are placed and not their direction. At least now I know where to look for reference.

This PR can be closed then. You might still want to apply the small fix in the README.

**Comment by donn** [comment]
No worries, we were confused about it reviewing this PR for a solid minute and had to take a look at the reference lol

**Comment by kareefardi** [comment]
@mole99 No worries. I would like to know if you ran into an issue and you tried to fix it through this PR.

**Comment by mole99** [comment]
@kareefardi I modified the io_place script and only because of my false understanding of X/Y I ran into an issue.

**Pull request closed without merging**
